sudo: required
services:
  - docker
python: '3.6'
before_install:
  - sudo apt-get install -y python3-pip
  - sudo python3 -m pip install pyyaml pylint
script:
  - if [[ "${TRAVIS_TAG}" == "v${TRAVIS_TAG#v}" ]]; then [[ "${TRAVIS_TAG#v}" != "$(cat VERSION)" ]] && exit 1 || echo "Version match"; fi
  - python3 -m pylint packagecore
  - ./setup.py test
  - ./setup.py sdist
  - sudo python3 -m pip install --upgrade --force-reinstall "dist/packagecore-$(cat VERSION).tar.gz"
  - if [[ "${TRAVIS_TAG}" == "v${TRAVIS_TAG#v}" ]]; then packagecore -o /tmp -C test 1.2.3 4 || exit 1; else packagecore -C test -o /tmp -p ubuntu18.04 1.2.3 4 || exit 1; fi
before_deploy:
  - packagecore "${TRAVIS_TAG#v}"
deploy:
  provider: releases
  api_key:
    secure: K6GvRJHsULvchyBsNCqGN5upgLvo0o7H0zxUxn9xs5Jzm13qvxw4/X5/f+vuKB8LRUF6x5c9eIXTXC3TnEOWq3PHrB1VZp4hIn+OXuEX0/J32dXTFgwDNLhldtn+/BrDlDoi6Gtc7hIvJSRzTEGbYtyqTPlwljl9mp+LfsJiHfBD/muEHrzUOYhlP7eGFrkuVLJ+Lu0EOE1LiHF7Z0+gdAdhtq6YGLy4N9elm4DN3HKYLYgGHG30ffypIJcSTFce3vdkqV0EsGjhqtCTm2OloAzlUGZ3EVXVC+AehFqUssSDpmvcMlFqogrL0tAz5/gQq1VnPJgGSVvgmg6gKZDnCJ9bgNQIfZEukwYIrY2AhKvsxoUB+vcNq0cdgdK3mgUm1e1lBTJYPkmQ2tU/D1UEql4bnmzMlanLYqDCJoMTMqu618DSlBqEWSxUwOiSFTyVou7oTHVQZGxs4DpkgWbI1XPSfaQfNniFvJzCe/Ca9ggt9WgG4SyHUsa/iwhS/pdERfspxXkdGRK92vkb3TjBBuKC6QBt0+BbCFneY6B/XNEf+tvMeqiLbLSDPdCQatD5fp7j1eCw3ybCa7SMIdUzfrgLmxnPysb5Mz0WIvraC3SaWsooUCDK3VTCDblwkq6sZNqYTKNobPXT2skdmZaYNLlUxPHKM2wA/aDpPAODkRw=
  file_glob: true
  file:
    - packagecore_*.deb
    - packagecore-*.pkg.tar.xz
    - packagecore-*.rpm
    - dist/packagecore-${TRAVIS_TAG#v}.tar.gz
  skip_cleanup: true
  on:
    tags: true
